[package]
name = "dygma-layer-switcher-ui"
version = "0.1.1"
edition = "2021"
authors = ["Matthew Wilding <mbwilding@gmail.com>"]

[dependencies]
common = { path = "../common" }
eframe = "0.23"

[build-dependencies]
embed-resource = "2.3"
